= CI/CD Hackathon for EMEA RHTE 2018
:toc:

== Goal

This lab is intended to expose you to the basic components of a continuous integration/continuous delivery (CI/CD) setup for Ansible playbooks and roles, and enable you to join us in the effort to work out a set of best practices.

Depending on you initial proficiency, you can either try out the existing set-up and tests or expand and improve them – or do something inbetween.

=== Minimal take-home message

If everything goes according to plan, after the lab, _every_ attendee should

* be able to explain what _CI/CD_ is
* know what _Git_ and _Jenkins_ are, and how they can interact in this context
* be able to perform basic configuration of a _Jenkins project_
* know what a _Jenkinsfile_ does
* have ran at least one test of a playbook
* have heard about _Molecule_

Of course, we hope that you leave this session with more new ideas than that. If you feel inspired to continue working on this, head over to https://github.com/redhat-cop/automate-cicd[GitHub] and join the https://mojo.redhat.com/community/communities-at-red-hat/management/automation-community-of-practice[Automation Community of Practice].

== CI/CD basics

.According to https://en.wikipedia.org/wiki/CI/CD[Wikipedia]:
[quote, English Wikipedia - CI/CD article]
In https://en.wikipedia.org/wiki/Software_engineering[software engineering], *CI/CD* or *CICD* may refer to the combined practices of https://en.wikipedia.org/wiki/Continuous_integration[continuous integration] and https://en.wikipedia.org/wiki/Continuous_delivery[continuous delivery].

This written, as we automate more and more and profess https://en.wikipedia.org/wiki/Infrastructure_as_Code[Infrastructure as Code] using Ansible, we also need to treat our playbooks as what they are, code, and test them accordingly, meaning automatically and regularly, because experience has shown that it is the only way to avoid technical debt and make sure that our infrastructure is properly tested before it goes in production.

Continuous Integration, which is the focus of this lab, offers following advantages:

- Automated testing during build creation, and potentially at deployment time.
- Gives fast feedback on errors
* before they impact operations.
* before changes are forgotten, cutting on root cause analysis
- Allow for continuous improvement by taking ITIL Problem Management lessons into new tests.
- Enable stress-less and successful rapid deployments, as test coverage grows, up to continuous deployment.
- Basis for a DevOps approach.


== Lab environment

The lab environment consists of a number of servers (not all of them running on dedicated machines) fulfilling the roles that are often found in a CI/CD environment.
It has been initially jointly created by the AMS and EMEA teams for the RHTE 2018 sessions.

TIP: if you're curious, check out the https://github.com/sborenst/ansible_agnostic_deployer/tree/development[Ansible agnostic deployer] repo, but it won't help you for this hackathon, so do it later.

=== Lab overview

All servers in this environment have an internal and an external name using the GUID associated to your environment on RHPDS:

- an external name: *NAME*.*GUID*.rhte.opentlc.com
- an internal name: *NAME*.*GUID*.internal

The servers have following names:

- bastion - this is the host through which you can easily connect to all the other ones.
- tower1 - the Ansible Tower server (it has a few pre-configured structures to help you get started)
* the Tower server is available under https://tower1.GUID.rhte.opentlc.com, the user is _admin_ (with the usual password). Tower is mostly there to give advanced attendees more options for experimentation, and has been setup with a few defaults structures.
- cicd1 - The CI/CD server (or build and test host) with Jenkins and Gogs pre-installed
* the Jenkins server is available under https://cicd1.GUID.rhte.opentlc.com:8443, the user is _admin_ (with the usual password); https://en.wikipedia.org/wiki/Jenkins_(software)[Jenkins] is an extremely popular CI tool that allows for automated building and testing of a codebase
* the Gogs server is available under http://cicd1.GUID.rhte.opentlc.com:3000 (the user is _cicduser1_, with the usual password); https://gogs.io/docs[Gogs] is a painless self-hosted Git service written in Go by Google (Go, go, go!).
- app1 and appdb1 - two "playground" hosts for you to test "stuff", the name implies a usage but you're really free to do what you want on those (they are connected to some standard RHEL repositories).

=== Lab connection

You may:

. Grab a GUID from the GuidGrabber at http://bit.ly/rhte-guidgrabber resp. https://www.opentlc.com/gg/gg.cgi?profile=rhtemgr (using the activation key provided by the presentator).
. connect to the bastion host via SSH using the credentials generated by the GuidGrabber: `ssh lab-user@bastion.GUID.rhte.opentlc.com`.
+
NOTE: it should have been fixed, but don't be surprised if the user doesn't have a home directory. Restart the bastion host and it'll be fixed.
+
. become root using `sudo -i`,
. from there jump to the other servers using the fully qualified _internal_ name (the user will be `ec2-user` but SSH is configured in such a way that you don't need to care).
+
TIP: as explained above, you can also use the Web UIs of Tower, Jenkins or Gogs to do your stuff.

NOTE: more detailed instructions can be found at https://github.com/RedHatDemos/RHTE-2018/blob/master/GG/gg-dedicated.adoc (but you shouldn't need them).


== Instructions

=== getting started

We'll assume in the following that you're already connected via SSH to the bastion host.

Depending on what you want to do, you have two options:

The easy way:: if you don't plan to provide extensions and just want to test the available examples (or don't have a GitHub account), you just can clone the repo with the examples on the bastion host `git clone https://github.com/redhat-cop/automate-cicd.git`, `cd automate-cicd/hackathons/rhte-2018-emea` and go from there into the first chosen showcase (see below).
The recommended way:: we'd really love to see your suggestions for improvements, hence you should:
.. fork the repository https://github.com/redhat-cop/automate-cicd into your own GitHub account,
.. clone the forked repository onto the bastion `git clone https://github.com/GITHUB-ACCOUNT/automate-cicd.git` (you can of course also work with SSH but then you'll need to handle the SSH keys)
.. `cd automate-cicd/hackathons/rhte-2018-emea`
.. configure Git with your name and e-mail: `git config --global user.name "Jim Whitehurst"` and `git config --global user.email "jim@redhat.com"`,
.. create a development branch `git checkout -b GITHUBACCOUNT-BRANCH-PURPOSE`,
.. try the examples and extend them (see below), or create your own example,
.. and finally push your extensions into a pull request `git push --set-upstream origin GITHUBACCOUNT-BRANCH-PURPOSE`
.. during the hackathon and later, create a pull request based on your branch.

CAUTION: everything you'll do will get **LOST** if you don't push your changes to your repository before the end of the Hackathon!

TIP: the repository will continue to live after the hackathon, so don't hesitate to work further on your branch after the Hackathon, and create a pull request (or more) later on. And if you have questions, the https://red.ht/autocop[Automation CoP] is here to help you (also in the channel #automation-cop on Rocket.Chat).

=== Available showcases

The following approaches are available to you, you may just use them and learn from them, or fix, improve or extend them, or even add your own approach if you've already gathered experience:

- link:example-pipeline[An example of an Ansible playbook being run from a Jenkins Pipeline. Contains instructions for setting up Jenkins Pipeline]
- link:callback-plugin-ci[use Ansible and the junit callback plug-in to test anything with Jenkins]
- link:example-molecule[use Molecule to test your roles]
- link:tower-plugin-jenkins[use the Tower plug-in for Jenkins and integrate Molecule testing in a pipeline]

=== Miscellaneous notes

- if you have issues with Firefox getting into a timeout during TLS handshake with the Tower server, it might be due to https://bugzilla.mozilla.org/show_bug.cgi?id=1474963[Bug 1474963 - Firefox stalls after TLS handshake on self signed certificate]. You have two choices:
* use another browser (Chromium works fine)
* call the following command: `cd ~/.mozilla/firefox/*.default/; while certutil -d sql:. -L | grep localhost; do certutil -d sql:. -D -n localhost; done` (`localhost` is the issue here because it's duplicated in the certificate database).

