= CI example =

This is a generic example of a CI setup as it was used in a consulting engagement.

== Getting started ==

Follow the instructions in https://github.com/redhat-cop/automate-cicd/blob/ericzolf-create-callback-job/hackathons/rhte-2018-emea/README.adoc[this README] and log in to bastion: `sudo ssh bastion.GUID.example.opentlc.com`.

== Jenkins setup ==

1. `cd automate-cicd/hackathons/rhte-2018-emea/callback-plugin-ci`
1. Replace `GUID` and `PASSWORD` and run `sudo ansible-playbook -i cicd1.GUID.internal setup_jenkins_job.yml -e 'usual_password=PASSWORD' -e 'guid=GUID'` to set up a Jenkins Project.
1. Open https://cicd1.GUID.rhte.opentlc.com:8443 in a browser and login as _admin_ (usual password)

== Triggering builds ==

To run your test-playbooks, open the project in Jenkins' WebGUI (https://cicd1.GUID.rhte.opentlc.com:8443/job/callback-plugin-ci/) and click on _Build with Parameters_. 
You can then select a directory and a pattern to chose which tests are ran. Keep all on default to trigger everything in `test_matrix`.

== Developing Tests ==

You can now write your own tests.
Go to `automate-cicd/hackathons/rhte-2018-emea/callback-plugin-ci/test_jenkins/test_matrix` and add test playbooks.
The pattern defined in the previous section is applied to the file name of the playbooks, so use a name that fits `test*.yml` to stay with the default example.
Before the testes are available from within Jenkins, you need to re-run the playbook from the _Jenkins setup_ section above.
